services:
  - type: web
    name: onyxaffilatestore
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        value: 3000
